version: "3.7"

services: 
  application:
    image: functionstest-application
    depends_on:
      - azurite
      - mongo
    build:
      context: ./src
      dockerfile: ./application/functionstest.application/dockerfile
    ports:
      - "7072:80"
    environment:
      - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;
      - functions_worker_runtime=dotnet

  persistence:
    image: functionstest-persistence
    depends_on:
      - azurite
      - mongo
    build:
      context: ./src
      dockerfile: ./persistence/functionstest.persistence/dockerfile
    ports:
      - "7073:80"
    environment:
      - MongoDatabaseName=FunctionsTest
      - MongoConnectionString=mongodb://root:P4ssword!@mongo:27017
      - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;
      - functions_worker_runtime=dotnet

  presentation:
    image: functionstest-presentation
    depends_on:
      - azurite
      - mongo
    build:
      context: ./src
      dockerfile: ./Presentation/FunctionsTest.Presentation/dockerfile
    ports:
      - "7071:80"
    environment:
      - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;
      - FUNCTIONS_WORKER_RUNTIME=dotnet
