version: "3.7"

services: 
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    entrypoint: azurite -l /workspace -d /workspace/debug.log --blobHost 0.0.0.0 --queueHost 0.0.0.0
    volumes:
      - d:/azure/azurite:/workspace
    expose:
      - 10000
      - 10001
    ports:
      - "10000:10000"
      - "10001:10001"
    
  mongo:
    image: mongo
    expose:
      - 27017
    ports:
      - "27017:27017"

  mongo-seed:
    build:
      context: .
      dockerfile: ./docker/seed.dockerfile
    image: test-seed
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    depends_on:
      - mongo
