version: "3.7"

services: 
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    entrypoint: azurite -l /workspace -d /workspace/debug.log --blobHost 0.0.0.0 --queueHost 0.0.0.0
    volumes:
      - c:/azurite:/workspace
    expose:
      - 10000
      - 10001
    ports:
      - "10000:10000"
      - "10001:10001"